### ISSUE TITLE
wrong prototype reference

### ISSUE THREAD

**Issue by xcel97** [Treast/binance.js#1]
Hey man,

I think the prototype reference for subAccountsUniversalTransfer is wrong as it calls
SubAccount_1.SubAccounts.prototype.**subAccountsList** 
instead of 
SubAccount_1.SubAccounts.prototype.**subAccountsUniversalTransfer**

Hope you can fix it soon
Cheers and thanks

Allan
https://github.com/Treast/binance.js/blob/783b9e76cca6d3ccb9bcabe7aea1bf24ee70b5e2/dist/Binance.js#L194

**Comment by Treast** [comment]
Thank you for the feedback.

Should be fixed in [v1.1.1](https://github.com/Treast/binance.js/releases/tag/1.1.1)
